.\" Manpage for blerp (See xkcd 1692)
.TH man 6 "10 June 2016" "0.0.1" "blerp"
.SH NAME
.PP
\fBblerp\fR
.SH SYNOPSIS
.PP
blerp {[OPTION | ARGS]...[ARGS... -f [FLAGS]...}
.PP
blerp {...\fIDIRECTORY\fR ... \fIURL\fR | \fIBLERP\fR} \fIOPTIONS\fR] -{}
.SH DESCRIPTION
blerp FILTERS LOCAL OR REMOTE FILES OR RESOURCES USING PATTERNS DEFINED BY
ARGUMENTS AND ENVIRONMENT VARIABLES. THIS BEHAVIOR CAN BE MODIFIED BY VARIOUS
FLAGS.
.SH OPTIONS
.TP
\fB\-a\fR ATTACK MDOE
.TP
\fB\-b\fR SUPPRESS BEES
.TP
\fB\-—\fR FLAGS USE EM DASHES
.TP
\fB\-c\fR COUNT NUMBER OF ARGUMENTS
.TP
\fB\-d\fR PIPES OUTPUT TO DEBUG.EXE
.TP
\fB\-D\fR DEPRECATED
.TP
\fB\-e\fR EXECUTE SOMETHING
.TP
\fB\-f\fR FUN MODE
.TP
\fB\-g\fR USE GOOGLE
.TP
\fB\-h\fR CHECK WETHER INPUT HALTS
.TP
\fB\-i\fR IGNORE CASE (LOWER)
.TP
\fB\-I\fR IGNORE CASE (UPPER)
.TP
\fB\-jk\fR KIDDING
.TP
\fB\-n\fR BEHAVIOR NOT DEFINED
.TP
\fB\-o\fR OVERWRITE
.TP
\fB\-O\fR OPPOSITE DAY
.TP
\fB\-p\fR SET TRUE POPE; ACCEPTS "ROME" OR "AVIGNON"
.TP
\fB\-q\fR QUIET MODE; OUTPUT IS PRINTED TO STDOUT INSETAD OF BEING SPOKEN ALOUD
.TP
\fB\-r\fR RANDOMIZE ARGUMENTS
.TP
\fB\-R\fR RUN RECURSIVLEY ON http://\*
.TP
\fB\-s\fR FOLLOW SYMBOLIC LINKS SYMBOLICALLY
.TP
\fB\-S\fR STEALTH MODE
.TP
\fB\-t\fR TUMBLE DRY
.TP
\fB\-u\fR UTF-8 MODE; OTHERWISE DEFAULTS TO ANSEL
.TP
\fB\-U\fR UPDATE (DEFAULT: FACEBOOK)
.TP
\fB\-v\fR VERBOSE; ALIAS TO find / \-exec cat {}
.TP
\fB\-V\fR SET VERSION NUMBER
.TP
\fB\-y\fR YIKES
.SH SEE ALSO
.PP
blerp(1), blerp(3), blirb(8), blarb(51), blorp(501)(c)(3)
.SH BUG REPORTS
http://inaturalist.org/taxa/47744\-Hemiptera
.SH COPYRIGHT
GPL(2)(3+) CC\-BY/5.0 RV 41.0 LIKE GECKO/BSD 4(2) OR BEST OFFER
